"""empty message

Revision ID: f0c7cad2bd84
Revises: 
Create Date: 2018-03-14 14:26:33.169083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c7cad2bd84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=64), nullable=True),
    sa.Column('feature_vector', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query')
    )
    op.create_table('neuralmodels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neurallayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('extracted', sa.Boolean(), nullable=True),
    sa.Column('neural_network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['neural_network_id'], ['neuralmodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neurallayer')
    op.drop_table('images')
    op.drop_table('neuralmodels')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
